[package]
name = "routair"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
futures-util = "0.3.31"
openai = "1.1.1"
pcap = "2.4.0"
rand = "0.9.2"
tokio = { version = "1.49.0", features = ["full"] }
warp = { version = "0.4.2", features = ["server", "websocket"] }
